config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "admin/merchants#index"

  namespace :admin do
    resources :transactions, only: %i[index show]
    resources :merchants, only: %i[index show edit update destroy]
  end

  scope module: :api do
    resources :transactions, only: %i[index show create]

    post 'auth/login', to: 'authentication#login'
    get '/*a', to: 'application#not_found'
  end
end

app/models/merchant.rb
# frozen_string_literal: true

class Merchant < User
  validates :name, presence: true

  def total_transaction_sum
    transactions.where(transactions: { type: 'Charge', status: 'approved' })
                .sum('transactions.amount')
  end

  def total_transactions
    transactions.size
  end
end

app/controllers/admin/merchants_controller.rb
# frozen_string_literal: true

class Admin::MerchantsController < ApplicationController
  before_action :set_merchant, only: %i[show edit update destroy]

  def index
    @merchants = Merchant.all.sort
  end

  def show; end

  def edit; end

  def update
    if @merchant.update(merchant_params)
      redirect_to admin_merchant_path(@merchant), notice: 'Merchant was successfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @merchant.destroy
      redirect_to root_path, notice: 'Merchant was successfully destroyed'
    else
      render 'admin/merchants/edit', status: :unprocessable_entity
    end
  end

  private

  def set_merchant
    @merchant ||= Merchant.find(params[:id])
  end

  def merchant_params
    params.require(:merchant).permit(
      :name, :email, :description, :status, :password, :password_confirmation
    )
  end
end

app/views/admin/merchants/edit.html.slim
= render 'admin/merchants/partials/form'

app/views/admin/merchants/index.html.slim
.content-wrapper
  #flash-messages
  - if notice
    p.alert.alert-success
      = notice
  - if alert
    p.alert.alert-danger
      = alert

  h1 Merchants #{link_to 'Transactions', admin_transactions_path, class: "btn btn-primary"}
  table.table
    thead
      tr
        th[scope="col"]
          | Name
        th[scope="col"]
          | Status
    tbody
      - @merchants.each do |merchant|
        tr
          td
            | #{link_to merchant.name, admin_merchant_path(merchant)}
          td
            | #{merchant.status}

app/views/admin/merchants/show.html.slim
.merchant
  #flash-messages
  - if notice
    p.alert.alert-success
      = notice
  - if alert
    p.alert.alert-danger
      = alert

  .card[style="width: 40rem;"]
    .card-body
      h3.card-title
        | #{@merchant.name} #{link_to 'Merchants', admin_merchants_path, class: "btn btn-primary"}
        | &nbsp;
        span
          = link_to 'edit', edit_admin_merchant_path(@merchant),
                            class: "btn btn-secondary"
      p.card-text
        b Status:
        | &nbsp;
        span #{@merchant.status}
      p.card-text
        b Email:
        | &nbsp;
        span #{@merchant.email}
      p.card-text
        b Description:
        | &nbsp;
        span #{@merchant.description}
      p.card-text
        b Transactions Count:
        | &nbsp;
        span #{@merchant.total_transactions}
      p.card-text
        b Transactions Sum:
        | &nbsp;
        span #{@merchant.total_transaction_sum}
      p.card-text
        b #{link_to 'Merchants transactions', admin_transactions_path(merchant_id: @merchant.id) }