config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "admin/merchants#index"

  namespace :admin do
    resources :transactions, only: %i[index show]
    resources :merchants, only: %i[index show edit update destroy]
  end

  scope module: :api do
    resources :transactions, only: %i[index show create]

    post 'auth/login', to: 'authentication#login'
    get '/*a', to: 'application#not_found'
  end
end

app/controllers/admin/transactions_controller.rb
# frozen_string_literal: true

class Admin::TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show]

  def index
    transactions =
      if params[:merchant_id].present?
        Transaction.where(user_id: params[:merchant_id]).group(:type, 'transactions.id')
      else
        Transaction.group(:customer_email, :type, 'transactions.id')
      end

    @transactions = transactions.order(created_at: :desc)
  end

  def show; end

  private

  def set_transaction
    @transaction ||= Transaction.find(params[:id])
  end
end

app/controllers/api/transactions_controller.rb
# frozen_string_literal: true

module Api
  class TransactionsController < Api::ApplicationController
    include ActionController::MimeResponds

    before_action :authorize_request
    before_action :check_merchant_status, only: :create
    before_action :validate_params, only: :create

    PERMITTED_PARAMS = %i[type amount customer_email customer_phone parent_id].freeze

    def index
      transactions = @current_user.transactions.group_by(&:customer_email)

      respond_to do |format|
        format.json do
          render json: transactions
        end
        format.xml do
          render xml: transactions.as_json
        end
      end
    end

    def show
      transaction = @current_user.transactions.find(params[:id])

      respond_to do |format|
        format.json do
          render json: transaction
        end
        format.xml do
          render xml: transaction.as_json
        end
      end
    end

    def create
      transaction = TransactionManager.call(transaction_params.merge(user_id: @current_user.id))

      if transaction
        respond_to do |format|
          format.json do
            render json: transaction, status: :created
          end
          format.xml do
            render xml: transaction.as_json, status: :created
          end
        end
      else
        respond_to do |format|
          format.json do
            render json: { errors: transaction.errors }, status: :unprocessable_entity
          end
          format.xml do
            render xml: { errors: transaction.errors.as_json }, status: :unprocessable_entity
          end
        end
      end
    end

    private

    def transaction_params
      if request.format.xml?
        fetch_xml_params
      elsif request.format.json?
        fetch_json_params
      else
        raise ActionController::UnknownFormat
      end
    end

    def fetch_json_params
      params.require(:transaction).permit(*PERMITTED_PARAMS)
    end

    def fetch_xml_params
      Hash.from_xml(request.raw_post)['hash']['transaction'].symbolize_keys.slice(*PERMITTED_PARAMS)
    rescue StandardError => _e
      {}
    end

    def validate_params
      validator = TransactionParamsValidator.new(transaction_params)

      return if validator.valid?

      respond_to do |format|
        format.json do
          render json: { errors: validator.errors }, status: :unprocessable_entity
        end
        format.xml do
          render xml: { errors: validator.errors.as_json }, status: :unprocessable_entity
        end
      end
    end
  end
end

app/views/admin/transactions/index.html.slim
.content-wrapper
  h1 Transactions #{link_to 'Merchants', admin_merchants_path, class: "btn btn-primary"}

  table.table
    thead
      tr
        th[scope="col"]
          | Id
        th[scope="col"]
          | Type
        th[scope="col"]
          | Amount
        th[scope="col"]
          | Status
        th[scope="col"]
          | Customer Email
        th[scope="col"]
          | Customer Phone
        th[scope="col"]
          | Merchant Id
        th[scope="col"]
          | Parent Transaction Id
        th[scope="col"]
          | Created At
        th[scope="col"]
          | Updated At
    tbody
      - @transactions.each do |transaction|
        tr
          td
            | #{link_to transaction.id, admin_transaction_path(transaction)}
          td
            | #{transaction.type}
          td
            | #{transaction.amount}
          td
            | #{transaction.status}
          td
            | #{transaction.customer_email}
          td
            | #{transaction.customer_phone}
          td
            | #{link_to transaction.user_id, admin_merchant_path(transaction.user_id)}
          td
            - if transaction.parent_id.present?
              | #{link_to transaction.parent_id, admin_transaction_path(transaction.parent_id)}
            - else
              |

          td
            | #{transaction.created_at}
          td
            | #{transaction.updated_at}

app/views/admin/transactions/show.html.slim
.merchant
  .card[style="width: 60rem;"]
    .card-body
      h5.card-title
        h3 Id: #{@transaction.id} &nbsp; #{link_to 'Transactions', admin_transactions_path, class: "btn btn-primary"}
      p.card-text
        b Type:
        | &nbsp;
        span #{@transaction.type}
      p.card-text
        b Amount:
        | &nbsp;
        span #{@transaction.amount}
      p.card-text
        b Status:
        | &nbsp;
        span #{@transaction.status}
      p.card-text
        b Customer Email:
        | &nbsp;
        span #{@transaction.customer_email}
      p.card-text
        b Customer Phone:
        | &nbsp;
        span #{@transaction.customer_phone}
      p.card-text
        b Merchant Id:
        | &nbsp;
        span #{link_to @transaction.user_id, admin_merchant_path(@transaction.user_id)}
      p.card-text
        b Parent Transaction Id:
        | &nbsp;
        span  #{@transaction.parent_id}
      p.card-text
        b Created At:
        | &nbsp;
        span #{@transaction.created_at}
      p.card-text
        b Updated At:
        | &nbsp;
        span #{@transaction.updated_at}